Vagrant.configure("2") do |config|
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.ssh.username = 'root'
    config.vm.network :private_network, ip: "192.168.121.10"
    config.ssh.private_key_path = ['id_rsa']
    config.ssh.forward_agent = true
    config.ssh.keys_only = false

    config.vm.provider :libvirt do |libvirt|
        libvirt.cpu_mode = 'host-passthrough'
        libvirt.driver = "kvm"
        libvirt.host = 'localhost'
        libvirt.uri = 'qemu:///system'
    end

    config.vm.define :centos do |centos|
        centos.vm.box = "centos"
        centos.vm.provider :libvirt do |test|
            test.memory = 1024
            test.cpus = 1
        end
    end
end